version: '2'
services:
    node:
        image: 'node:8'
        user: 'node'
        working_dir: /home/node/app
        environment:
            - NODE_ENV=production
        volumes:
            - ./:/home/node/app
        ports:
            - 8888:8888
        expose:
            - '8888'
        command: 'npm run start'
